<!DOCTYPE html>
<html><head><title>Exception</title><link rel="stylesheet" href="../../styles.css"/><script src="../../scripts.js"></script></head><body onload="ro();">
<div class="rH">3 overrides of Exception</div><div class="rA">Assembly-CSharp-firstpass (3)</div><div class="rG" id="Assembly-CSharp-firstpass"><div class="rF"><div class="rN">Assets\Plugins\UniRx\Scripts\Notification.cs (3)</div>
<a href="../Assets/Plugins/UniRx/Scripts/Notification.cs.html#144"><b>144</b>public override Exception <i>Exception</i> { get { return null; } }</a>
<a href="../Assets/Plugins/UniRx/Scripts/Notification.cs.html#278"><b>278</b>public override Exception <i>Exception</i> { get { return exception; } }</a>
<a href="../Assets/Plugins/UniRx/Scripts/Notification.cs.html#405"><b>405</b>public override Exception <i>Exception</i> { get { return null; } }</a>
</div>
</div>
<div class="rH">4 references to Exception</div><div class="rA">Assembly-CSharp (2)</div><div class="rG" id="Assembly-CSharp"><div class="rF"><div class="rN">Assets\UnitTests\UnitTests.cs (2)</div>
<a href="../../Assembly-CSharp/Assets/UnitTests/UnitTests.cs.html#7432"><b>7432</b>xs[1].<i>Exception</i>.IsInstanceOf&lt;TimeoutException&gt;();</a>
<a href="../../Assembly-CSharp/Assets/UnitTests/UnitTests.cs.html#7456"><b>7456</b>xs[2].<i>Exception</i>.IsInstanceOf&lt;TimeoutException&gt;();</a>
</div>
</div>
<div class="rA">Assembly-CSharp-firstpass (2)</div><div class="rG" id="Assembly-CSharp-firstpass"><div class="rF"><div class="rN">Assets\Plugins\UniRx\Scripts\Notification.cs (1)</div>
<a href="../Assets/Plugins/UniRx/Scripts/Notification.cs.html#309"><b>309</b>return Object.Equals(Exception, other.<i>Exception</i>);</a>
</div>
<div class="rF"><div class="rN">Assets\Plugins\UniRx\Scripts\Operators\Dematerialize.cs (1)</div>
<a href="../Assets/Plugins/UniRx/Scripts/Operators/Dematerialize.cs.html#43"><b>43</b>try { observer.OnError(value.<i>Exception</i>); }</a>
</div>
</div>
</body></html>